sudo: false  # use new container infrastructure on Travis CI

language: python

python: 3.11

before_install:
  # Make a virtualenv
  - python -m venv .venv

install:
  # Activate virtaulenv
  - source .venv/bin/activate

  # TODO: Remove once on PyPI
  # Install nilm_metadata (development version)
  - pip install 'git+https://github.com/VorobiovM/nilm_metadata/tree/feature/setuptools_and_wheels_distribution#egg=nilm_metadata'

  # Finally, install nilmtk (development version)
  - pip install -e .[dev]

script:
  - python -c 'from nilmtk.utils import show_versions; show_versions()'
  - nosetests

after_script:
  - source deactivate

cache:
  directories:
    - $HOME/.cache/pip
